name: forge
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fsspec
  - datashader
  - geopandas
  - geoviews
  - hvplot
  - intake
  - intake-xarray
  - intake-stac
  - jupyterlab=3
  - jupyter-panel-proxy
  - panel
  - rasterio
  - rioxarray
  - sat-search
  - sat-stac
  - xarray
  - qgis
  - gdal
  - pyviz_comms
  - holoviews
  - bokeh
  - nodejs
  - param
  - progressbar2